07_map/articles/urls.py
from django.urls import path
from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'), # GET(new) / POST(create)
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'), # GET(edit) / POST(update)
    path('<int:pk>/delete/', views.delete, name='delete')
]

07_map/crud/urls.py
from django.contrib import admin
from django.urls import path, include
from articles import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('', views.index),
]

07_map/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    lat = models.FloatField() 
    lng = models.FloatField()
    
    

07_map/articles/forms.py
from django import forms
from .models import Article

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = '__all__'

07_map/articles/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_http_methods, require_POST
from .models import Article
from .forms import ArticleForm
from django.core.paginator import Paginator


# Pagination 구현
def index(request):
    articles = Article.objects.all()
    paginator = Paginator(articles, 2)  # articles을 2개씩 나눠주는 paginator 인스턴스 생성
    page_number = request.GET.get('page') # GET 요청이 ?page=숫자  형식으로 올거임.
    articles = paginator.get_page(page_number)

    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)


@require_http_methods(['GET', 'POST'])
def create(request):
    # http method POST 일 때
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            article = form.save()
            return redirect('articles:detail', article.pk)
    # POST가 아닌 다른 methods 일 때
    else: 
        form = ArticleForm()
    context = {
        # form 2가지 모습
        # 1. is_valid()에서 통과하지 못한 form (에러메세지를 포함)
        # 2. else 구문의 form
        'form': form,
    }
    return render(request, 'articles/create.html', context)


def detail(request, pk):
    article = Article.objects.get(pk=pk)
    context = {
        'article': article,
    }
    return render(request, 'articles/detail.html', context)


@require_http_methods(['GET', 'POST'])
def update(request, pk):
    article = Article.objects.get(pk=pk)
    if request.method == 'POST':
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm(instance=article)
    context = {
        'form': form,
    }
    return render(request, 'articles/update.html', context)


@require_POST
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    article.delete()
    return redirect('articles:index') 

07_map/articles/templates/articles/create.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
<h1>NEW</h1>
<div id="map" style="width:500px;height:400px;"></div>
<form action="{% url 'articles:create' %}" method="POST">
  {% csrf_token %}
  {% bootstrap_form form%}
  <button class="btn btn-primary">작성</button>
</form>

<script>
  //1. 지도를 그릴 공간을 찾기
  var container = document.querySelector('#map'); //지도를 담을 영역의 DOM 레퍼런스

  //2. 지도 옵션 설정
  var options = { //지도를 생성할 때 필요한 기본 옵션
    center: new kakao.maps.LatLng(33.450701, 126.570667), //지도의 중심좌표.
    level: 3, //지도의 레벨(확대, 축소 정도)    
  };

  //3. 지도 객체 생성
  var map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴
  
  //4. 마커 그리기
  // 4-1. 마커 객체 생성
  var marker = new kakao.maps.Marker({ 
      // 지도 중심좌표에 마커를 생성합니다 
      position: map.getCenter() 
  }); 
  // 4-2. 지도에 마커 표시
  marker.setMap(map);

 
 
//5. 지도에 클릭 이벤트를 등록합니다
// 지도를 클릭하면 마지막 파라미터로 넘어온 함수를 호출합니다
    kakao.maps.event.addListener(map, 'click', function(mouseEvent) {        
    
    // 클릭한 위도, 경도 정보를 가져옵니다 
    var latlng = mouseEvent.latLng; 
    
    // 마커 위치를 클릭한 위치로 옮깁니다
    marker.setPosition(latlng);
    
    //위도
    var latInput = document.querySelector('#id_lat')  // input 필드 찾아오기
    latInput.value = latlng.getLat();

    //경도
    var lngInput = document.querySelector('#id_lng') // input 필드 찾아오기
    lngInput.value = latlng.getLng();
    
});


</script>


{% endblock %}

07_map/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>DETAIL</h1>
  <h2>{{ article.pk }} 번 글</h2>
  <hr>
  <p>제목 : {{ article.title }}</p>
  <p>내용 : {{ article.content }}</p>
  <p>작성 시각 : {{ article.created_at }}</p>
  <p>수정 시각 : {{ article.updated_at }}</p>
  <p>위도 : {{ article.lat }}</p>
  <p>경도 : {{ article.lng }}</p>
  <div id="map" style="width:100%;height:350px;"></div>
  <hr>
  <a class="btn btn-warning" href="{% url 'articles:update' article.pk %}">update</a>
  <form action="{% url 'articles:delete' article.pk %}" method='POST'>
    {% csrf_token %}
    <button class="btn btn-danger">delete</button>
  </form>
  <a class="btn btn-secondary" href="{% url 'articles:index' %}">back</a>

  <script>
    //1. 지도를 그릴 공간을 찾기
    var container = document.querySelector('#map'); //지도를 담을 영역의 DOM 레퍼런스

    //2. 지도 옵션 설정
    var options = {
      center: new kakao.maps.LatLng( {{ article.lat }},{{ article.lng }} ), //지도의 중심좌표.
      level: 3, //지도의 레벨(확대, 축소 정도)    
    };

    //3. 지도 객체 생성
    var map = new kakao.maps.Map(container, options); //지도 생성 및 객체 리턴

    //4. 마커 그리기
    // 4-1. 마커 객체 생성
    var marker = new kakao.maps.Marker({ 
        // 지도 중심좌표에 마커를 생성합니다 
        position: map.getCenter() 
    }); 
    // 4-2. 지도에 마커 표시
    marker.setMap(map);


  </script>
{% endblock %}

07_map/articles/templates/articles/index.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block content %}
  <h1 class="text-center">Articles</h1>
  <a href="{% url 'articles:create' %}">NEW</a>
  <hr>
  {% for article in articles %}
    <p>글 번호 : {{ article.pk }}</p>
    <p>글 제목 : {{ article.title }}</p>
    <p>글 내용 : {{ article.content }}</p>
    <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
    <hr> 
  {% endfor %}
    <div class="pagination">
        <span class="step-links">
            {% if articles.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ articles.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ articles.number }} of {{ articles.paginator.num_pages }}.
            </span>

            {% if articles.has_next %}
                <a href="?page={{ articles.next_page_number }}">next</a>
                <a href="?page={{ articles.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>

    {% bootstrap_pagination articles %}
{% endblock %}

07_map/articles/templates/articles/update.html
{% extends 'base.html' %}
{% load bootstrap4 %}


{% block content %}
<h1>UPDATE</h1>
<form action="" method="POST">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>
{% endblock %}

07_map/crud/templates/base.html
{% load bootstrap4 %}

<!DOCTYPE html>
<html lang="ko">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
  <script type="text/javascript" src="//dapi.kakao.com/v2/maps/sdk.js?appkey=67d2f5167f9c27692d692cf6495adf35"></script>
</head>
<body>
  <div class="container">
  
    {% block content %}
    {% endblock %}
  </div>
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>