01_django_orm/firstapp/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'), # 글작성
    path('create/', views.create, name='create'), # 글저장
    path('<int:pk>/', views.detail, name='detail'), # 글보기
    path('<int:pk>/delete/', views.delete, name='delete'), # 삭제
    path('<int:pk>/edit/', views.edit, name='edit'), # 글수정
    path('<int:pk>/update/', views.update, name='update'), # 수정저장
]

01_django_orm/firstapp/firstapp/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls'))
]

01_django_orm/firstapp/articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)  # 데이터베이스의 최초 생성일
    updated_at = models.DateTimeField(auto_now=True) # 데이터 최신 수정일

01_django_orm/firstapp/articles/views.py
from django.shortcuts import render, redirect
from .models import Article

# Create your views here.
# 전체 글 보기
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

# 게시글 입력용 화면
def new(request):
    return render(request, 'articles/new.html')

# 게시글 저장
def create(request):
    # 1. new 에서 보낸 데이터 받기
    title = request.POST.get('title')
    content = request.POST.get('content')

    # 2. db에 저장하기
    # # 방법1 : 인스턴스 생성하고 세팅
    # article = Article()
    # article.title = title
    # article.content = content
    # article.save()

    # # 방법2 : 세팅값 주면서 인스턴스 생성
    article = Article(title=title, content=content)
    article.save()

    # # 방법3 : 인스턴스 생성 메소드 사용 --- 데이터 유효성 검사 타이밍이 없다.
    # Article.objects.create(title=title, content=content)    
    # return redirect('articles:index') # 요청을 index로 보낸다.
    return redirect('articles:detail', article.pk) # 요청을 detail로 보낸다. (pk를 함께 보내준다.)

# pk로 게시글 조회
def detail(request, pk):
    article = Article.objects.get(pk=pk) # 글을 찾고
    context = {
        'article' : article,
    }
    return render(request, 'articles/detail.html', context)

# DELETE
def delete(request, pk):
    print(request.method)
    article = Article.objects.get(pk=pk)
    # POST 일 때 만 동작하도록 분기
    if request.method == 'POST':
        article.delete()
        return redirect('articles:index')
    else:
        return redirect('articles:detail', pk)

# 수정하는 화면
def edit(request, pk):
    article = Article.objects.get(pk=pk) # 특정하고
    context = {
        'article': article,
    }
    return render(request, 'articles/edit.html', context)

# UPDATE 실행
def update(request, pk):
    # 1. 수정할 게시글 조회
    article = Article.objects.get(pk=pk) # 특정하고
    # 2. edit에서 보낸 데이터를 받아서 기존 값을 업데이트
    article.title = request.POST.get('title')  # 내용 변경
    article.content = request.POST.get('content') # 내용 변경
    article.save()    # 저장
    return redirect('articles:detail', pk)

01_django_orm/firstapp/articles/templates/articles/create.html
{% extends 'base.html' %}

{% block content %}
    <h2>글이 정상적으로 작성되었습니다.</h2>
    <a href="{% url 'articles:index' %}">글 보기</a>
{% endblock  %}

01_django_orm/firstapp/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<h2>{{ article.pk }}번 글</h2>
<hr>
<p>제목 :{{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>작성 시각 : {{ article.created_at }}</p>
<p>수정 시각 : {{ article.updated_at }}</p>
<hr>
<!--<a href="{% url 'articles:delete' article.pk %}">DELETE</a> -->
<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button>삭제</button>
</form>
<a href="{% url 'articles:index' %}">back</a><br>
<a href="{% url 'articles:edit' article.pk %}">EDIT</a>
{% endblock  %}

01_django_orm/firstapp/articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block content %}
    <h1>EDIT</h1>
    <form action="{% url 'articles:update' article.pk %}" method="POST">
        {% csrf_token %}
        <input type="text" name="title" value="{{ article.title }}"><br>
        <textarea name="content">{{ article.content }}</textarea><br>
        <button class="btn btn-primary">수정</button>
    </form>
{% endblock  %}

01_django_orm/firstapp/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block  content %}
    <h1 class="text-center">Articles</h1>
    <a href="{% url 'articles:new' %}">NEW</a>
    <hr>
    {% for  article in articles %}
        <p>글 번호 :{{ article.pk }}</p>
        <p>글 제목 :{{ article.title }}</p>
        <p>글 내용 :{{ article.content }}</p>
        <p>글 수정일 :{{ article.updated_at }}</p>
        <a href="{% url 'articles:detail' article.pk %}">DETAIL</a>
        <hr>
    {% endfor %}
{% endblock  %}

01_django_orm/firstapp/articles/templates/articles/new.html
{% extends 'base.html' %}

{% block content %}
    <h1>NEW</h1>
    <form action="{% url 'articles:create' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="title"><br>
        <textarea name="content"></textarea><br>
        <button class="btn btn-primary">작성</button>
    </form>
{% endblock  %}

01_django_orm/firstapp/articles/templates/articles/update.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<h2>{{ article.pk }}번 글</h2>
<hr>
<p>제목 :{{ article.title }}</p>
<p>내용 : {{ article.content }}</p>
<p>작성 시각 : {{ article.created_at }}</p>
<p>수정 시각 : {{ article.updated_at }}</p>
<hr>
<!--<a href="{% url 'articles:delete' article.pk %}">DELETE</a> -->
<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <button>삭제</button>
</form>
<a href="{% url 'articles:index' %}">back</a><br>
<a href="{% url 'articles:edit' article.pk %}">EDIT</a>
{% endblock  %}

01_django_orm/firstapp/firstapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
</head>
<body>    
    <div class="container">
        {% block content %}
        {% endblock  %}
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
</body>
</html>